dsffsfds/config/routes.rb
Rails.application.routes.draw do
  resources :asswipes

end

dsffsfds/app/models/asswipe.rb
class Asswipe < ActiveRecord::Base
end

dsffsfds/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

dsffsfds/app/controllers/asswipes_controller.rb
class AsswipesController < ApplicationController
  before_action :set_asswipe, only: [:show, :edit, :update, :destroy]

  # GET /asswipes
  # GET /asswipes.json
  def index
    @asswipes = Asswipe.all
  end

  # GET /asswipes/1
  # GET /asswipes/1.json
  def show
  end

  # GET /asswipes/new
  def new
    @asswipe = Asswipe.new
  end

  # GET /asswipes/1/edit
  def edit
  end

  # POST /asswipes
  # POST /asswipes.json
  def create
    @asswipe = Asswipe.new(asswipe_params)

    respond_to do |format|
      if @asswipe.save
        format.html { redirect_to @asswipe, notice: 'Asswipe was successfully created.' }
        format.json { render :show, status: :created, location: @asswipe }
      else
        format.html { render :new }
        format.json { render json: @asswipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asswipes/1
  # PATCH/PUT /asswipes/1.json
  def update
    respond_to do |format|
      if @asswipe.update(asswipe_params)
        format.html { redirect_to @asswipe, notice: 'Asswipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @asswipe }
      else
        format.html { render :edit }
        format.json { render json: @asswipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asswipes/1
  # DELETE /asswipes/1.json
  def destroy
    @asswipe.destroy
    respond_to do |format|
      format.html { redirect_to asswipes_url, notice: 'Asswipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asswipe
      @asswipe = Asswipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asswipe_params
      params.require(:asswipe).permit(:name)
    end
end

dsffsfds/app/helpers/application_helper.rb
module ApplicationHelper
end

dsffsfds/app/helpers/asswipes_helper.rb
module AsswipesHelper
end

dsffsfds/app/views/asswipes/_form.html.erb
<%= form_for(@asswipe) do |f| %>
  <% if @asswipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asswipe.errors.count, "error") %> prohibited this asswipe from being saved:</h2>

      <ul>
      <% @asswipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dsffsfds/app/views/asswipes/edit.html.erb
<h1>Editing asswipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @asswipe %> |
<%= link_to 'Back', asswipes_path %>

dsffsfds/app/views/asswipes/index.html.erb
<h1>Listing asswipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asswipes.each do |asswipe| %>
      <tr>
        <td><%= asswipe.name %></td>
        <td><%= link_to 'Show', asswipe %></td>
        <td><%= link_to 'Edit', edit_asswipe_path(asswipe) %></td>
        <td><%= link_to 'Destroy', asswipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asswipe', new_asswipe_path %>

dsffsfds/app/views/asswipes/new.html.erb
<h1>New asswipe</h1>

<%= render 'form' %>

<%= link_to 'Back', asswipes_path %>

dsffsfds/app/views/asswipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @asswipe.name %>
</p>

<%= link_to 'Edit', edit_asswipe_path(@asswipe) %> |
<%= link_to 'Back', asswipes_path %>